package by.tc.sshop.controller;

enum CommandName {
    LOG_IN, REGISTER, LOG_OUT, USER_PAGE, VIEW_USER, VIEW_USERS,
    ADD_BIKE, UPDATE_BIKE, VIEW_BIKES, BIKE_BY_ID, BIKES_BY_BRAND, BIKES_BY_WHEELDIAM,
    ADD_COMMENT,UPDATE_COMMENT
}
